datadir: ${hydra:runtime.cwd}
filenames: null
chunk: 300
tmp_pre: add_metrics.list
invalidate_cache: False

design_metrics:
  - backbone

sequence_metrics:
  - default

slurm:
  J: null
  p: cpu
  gres: null
  submit: True
  in_proc: False
  keep_logs: True
