defaults:
  - pipeline

sweep:
  command_args: >
    --config-name=aa
    inference.ckpt_path=
      /net/scratch/ahern/se3_diffusion/training/fm_tip_resume_24/fm_tip_resume_242023-12-03_14:20:34.490797/rank_0/models/RFD_44.pt
    diffuser.T=50
    inference.deterministic=True
  benchmark_json: demo.json
  benchmarks: all
  num_per_condition: 1
  num_per_job: 1
  stop_step: sweep

outdir: /net/scratch/${oc.env:USER}/se3_diffusion/benchmarks/${now:%Y-%m-%d}_${now:%H-%M-%S}_demo