# Base inference Configuration.
defaults:
  - base

inference:
  align_motif: False
  str_self_cond: True

score_model:
  weights_path: /net/scratch/ahern/se3_diffusion/training/from_scratch_4_resume_ep16/train_session2023-06-29_1688072531.6048305/models/RFD_30.pt
