defaults:
  - debug

inference:
  output_prefix: debug/aa_small
  model_runner: NRBStyleSelfCond
  input_pdb: 'benchmark/input/gaa.pdb'
  guidepost_xyz_as_design: True
  guidepost_xyz_as_design_bb: [True]
  contig_as_guidepost: False
  str_self_cond: 1
  ckpt_path: /net/scratch/ahern/se3_diffusion/training/fm_tip_resume_24/fm_tip_resume_242023-12-03_14:20:34.490797/rank_0/models/RFD_45.pt

dataloader:
  P_IS_GUIDEPOST_EXAMPLE: 0.5

contigmap:
  contigs: ['10,A518-518,1']
