# Base inference Configuration.
defaults:
  - base

guidepost_bonds: True

inference:
  align_motif: False
  str_self_cond: False
  state_dict_to_use: model_state_dict
  deterministic: False
  ckpt_path: /net/databases/lab/aa-diffusion/models/RFD_140_ORI_tipatom.pt
  idealize_sidechain_outputs: True
idealization_metric_n_steps: 50

diffuser:
  T: 100
  trans:
    sample_schedule: linear
    exp_rate: 1
  rots:
    sample_schedule: normed_exp
    exp_rate: 10
