# Base inference Configuration.

inference:
  input_pdb: rf_diffusion/test_data/1qys.pdb
  num_designs: 10
  design_startnum: 0
  ckpt_path: /net/scratch/ahern/se3_diffusion/training/fm_tip_resume_24/fm_tip_resume_242023-12-03_14:20:34.490797/rank_0/models/RFD_44.pt
  ppi_design: False
  autogenerate_contigs: False
  symmetry: null
  recenter: True
  radius: 10.0
  model_only_neighbors: False
  num_recycles: 1
  recycle_schedule: null
  softmax_T: 1e-5
  output_prefix: samples/design
  write_trajectory: False # Boolean. Should the /traj/ video pdb file be generated? Takes up a lot of space in production
  write_trajectory_only_t: [] # list(int). Only write trajectory for these given t steps. Example: [50,40,30,20]
  write_trb: True # Boolean. Should the .trb file be written?
  write_trb_indep: False # Boolean. Should the indep be written to the .trb? Adds about 200KB to trb
  write_trb_trajectory: False # Boolean. Should the trajectory be written to the .trb? Adds about 10MB to trb
  scaffold_guided: False
  model_runner: NRBStyleSelfCond
  cautious: True
  recycle_between: False
  align_motif: True
  autoregressive_confidence: True
  no_confidence: True
  use_jw_selfcond: False
  symmetric_self_cond: True
  final_step: 1
  feed_true_xt: False
  deterministic: False
  zero_weights: False
  ligand: null
  ema: True
  contig_as_guidepost: False
  remove_guideposts_from_output: True
  state_dict_to_load: model_state_dict
  infer_guidepost_positions: True
  guidepost_xyz_as_design: True
  guidepost_xyz_as_design_bb: [False]
  conditions:
    relative_sasa:
      mean: 0.5
      std: 3.0
    radius_of_gyration:
      mean: 15
      std: 20
    radius_of_gyration_v2:
      active: False
      rog: -1
    relative_sasa_v2:
      active: False
      rasa: -1
    little_t_embedding: null
    sinusoidal_timestep_embedding: null
  safety:
    # Indicates that a user is carefully performing sidechain partial diffusion.
    # We require this to be set, as unless a user is careful this causes undefined behavior.
    sidechain_partial_diffusion: False
  flexible_ligand: False
  center_motif: True
  classifier_free_guidance_scale: 1
  idealize_sidechain_outputs: False
  recenter_xt: False
  update_seq_t: False

contigmap:
  contigs: ['20', 'A3-23', '30']
  contig_atoms: null
  inpaint_str: null
  inpaint_seq: null
  length: null
  shuffle: null
  has_termini: [True]
  intersperse: null

rf:
  model:
    use_chiral_l1: ${model.use_chiral_l1}
    use_lj_l1: ${model.use_lj_l1}
    use_atom_frames: ${model.use_atom_frames}
    use_same_chain: ${model.use_same_chain}
    recycling_type: ${model.recycling_type}
    enable_same_chain: ${model.enable_same_chain}
    refiner_topk: ${model.refiner_topk}
    get_quaternion: ${model.get_quaternion}

model:
  use_chiral_l1: True
  use_lj_l1: True
  use_atom_frames: True
  use_same_chain: True
  recycling_type: all
  enable_same_chain: True
  refiner_topk: 128
  get_quaternion: True
  n_extra_block: 4
  n_main_block: 32
  n_ref_block: 4
  d_msa: 256
  d_msa_full: 64
  d_pair: 128
  d_templ: 64
  n_head_msa: 8
  n_head_pair: 4
  n_head_templ: 4
  d_hidden: 32
  d_hidden_templ: 32
  p_drop: 0.15
  SE3_param:
    num_layers: -1
    num_channels: -1
    num_degrees: -1
    n_heads: -1
    div: -1
    l0_in_features: -1
    l0_out_features: -1
    l1_in_features: -1
    l1_out_features: -1
    num_edge_features: -1
  SE3_ref_param:
    n_extra_block: -1
    n_main_block: -1
    n_ref_block: -1
    n_finetune_block: -1
    d_msa: -1
    d_msa_full: -1
    d_pair: -1
    d_templ: -1
    n_head_msa: -1
    n_head_pair: -1
    n_head_templ: -1
    d_hidden: -1
    d_hidden_templ: -1
    p_drop: -1
    use_extra_l1: -1
    use_atom_frames: -1
    freeze_track_motif: -1
  freeze_track_motif: False
  symmetrize_repeats: False
  repeat_length: null
  symmsub_k: null
  sym_method: mean
  copy_main_block_template: False
  main_block: null

diffuser:
  T: 200
  partial_T: null    
  aa_decode_steps: 40
  so3:
    use_cached_score: false
  preserve_motif_sidechains: false

seq_diffuser:
  s_b0: null
  s_bT: null
  schedule_type: null
  loss_type: null
  seqdiff: null

denoiser:
  noise_scale: 1
  noise_scale_ca: 1
  noise_scale_frame: 1
  noise_scale_torsion: 1
  center: False

ppi:
  hotspot_res: null
  binderlen: null

potentials:
  guiding_potentials: null 
  guide_scale: 10
  guide_decay: constant
  olig_inter_all : null
  olig_intra_all : null
  olig_custom_contact : null

contig_settings:
  ref_idx: null
  hal_idx: null
  idx_rf: null
  inpaint_seq_tensor: null
  inpaint_str_tensor: null

preprocess:
  sidechain_input: False
  motif_sidechain_input: True
  sequence_decode: True
  d_t1d: 22
  d_t2d: 44
  prob_self_cond: 0.0
  str_self_cond: False
  seq_self_cond: False
  predict_previous: False
  randomize_frames: False
  annotate_termini: True
  use_cb_to_get_pair_dist: True
  
logging:
  inputs: False

extra_tXd_params: {}

upstream_inference_transforms: # Transforms that are only applied for inference. Likely have similar-but-different training copies
  names: []
  configs: {}

transforms:
  configs:
    # Default inference overrides for transforms regardless if they are used or not in the original model
    CenterPostTransform:
      jitter: 0.0
    AddConditionalInputs:
      p_is_guidepost_example: ${inference.contig_as_guidepost}
      guidepost_bonds: ${guidepost_bonds}
    ExpandConditionsDict: {}
