defaults:
  - fm_tip

upstream_training_transforms:
  names:
    - PopMask

  configs:  
    PopMask: {}

transforms:
  names:
    - AddConditionalInputs
    - CenterPostTransform

  configs:
    CenterPostTransform:
      jitter: 0.0
      jitter_clip: 20.0
    AddConditionalInputs:
      p_is_guidepost_example: ${....dataloader.P_IS_GUIDEPOST_EXAMPLE}
      guidepost_bonds: ${....guidepost_bonds}    

benchmark:
  pipeline_yaml: 'training_benchmarks_ORI.yaml'