defaults:
  - fm_tip

transforms:
  names:  
    - PopMask
    - AddConditionalInputs
    - CenterPostTranform

  configs:
    PopMask: {}
    CenterPostTranform:
      jitter: 5.0
      jitter_clip: 20.0
    AddConditionalInputs:
      p_is_guidepost_example: ${....dataloader.P_IS_GUIDEPOST_EXAMPLE}
      guidepost_bonds: ${....guidepost_bonds}    

benchmark:
  pipeline_yaml: 'training_benchmarks_ORI.yaml'