defaults:
  - toy_bonds_continuous_time

metrics:
- atom_bonds
- VarianceNormalizedPredTransMSE
- VarianceNormalizedInputTransMSE

experiment:
  diffuse_everything: false

dataloader:
  max_residues: 10
  CROP: 50

n_write_pdb: 1
pseudobatch: 24
ckpt_load_path: /home/ahern/projects/aa/rf_diffusion/models/RFD_36_cont_time.pt