defaults:
  - RFD_36

guidepost_bonds: false

dataloader:
  CROP: 10
  USE_GUIDE_POSTS: false
  DATASETS: pdb_aa
  DATASET_PROB: [1.0]
  DIFF_MASK_PROBS:
    atomize_all_res: 1.0
    get_closest_tip_atoms: 0.0
    get_unconditional_diffusion_mask: 0.0
    get_diffusion_mask_islands: 0.0
    get_closest_tip_atoms_partial_ligand: 0.0
    get_diffusion_mask_islands_partial_ligand: 0.0
    get_unconditional_diffusion_mask_partial_ligand: 0.0
  DATAPKL_AA: /home/dtischer/code/rf_diffusion_train/rf_diffusion/aa_dataset_256.pkl

experiment:
  c6d_loss_weight: 0.0
  diffuse_everything: true

diffuser:
  time_type: discrete

ckpt_load_path: /net/scratch/ahern/se3_diffusion/training/covale_complex_from_str_pred_batch24_l40_fallback_2/2023-08-03_1691112266.2135339_v4znb6v8/rank_0/models/RFD_36.pt
n_write_pdb: 10
resume_scheduler: false
